baseURL = "https://RONY-1.github.io/Hugo-Portfolio/"
title = "Portfolio"
theme = "PaperMod"
languageCode = "en-us"
defaultContentLanguage = "en"

summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  env = "production"
  title = "Portfolio"
  description = "MSc Student in CSE (Data Science) | Undergraduate Research Assistant | ML & DL Trainer"
  author = "Md. Rony"

  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true

  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

  [params.profileMode]
    enabled = true
    title = "Hi, I’m Md. Rony 👋"
    subtitle = "Currently pursuing an **MSc in Computer Science & Engineering (Major in Data Science)** at Daffodil International University. Aspiring to become a university lecturer and pursue a PhD in Computer Science & Engineering, specializing in Data Science, Machine Learning, and Deep Learning.\n\n**Current Positions**\n- **MSc Student in CSE (Major in Data Science)** @ Daffodil International University\n- **Undergraduate Research Assistant (RA)** @ DIU NLP and ML Research Lab\n- **Trainer** - Advanced Machine Learning & Deep Learning Bootcamp (Trained 100+ Students)\n- **Communication Secretary** @ DIU Cyber Security Club\n\n**Research Focus**\nData Science, Deep Learning, Natural Language Processing (NLP), Explainable AI (XAI), and Computer Vision."
    imageUrl = "images/profile.png"
    imageWidth = 150
    imageHeight = 150
    imageTitle = "Md. Rony"

    [[params.profileMode.buttons]]
      name = "Research Publications"
      url = "/publications/"

    [[params.profileMode.buttons]]
      name = "Projects"
      url = "/projects/"

    [[params.profileMode.buttons]]
      name = "Full CV"
      url = "/cv/"

    [[params.profileMode.buttons]]
      name = "Search"
      url = "/search/"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/md-rony-4a8512253/"

  [[params.socialIcons]]
    name = "facebook"
    url = "https://www.facebook.com/share/17YqGNVQn6/"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:rony15-4967@gmail.com"

[menu]
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 10

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 20

  [[menu.main]]
    name = "Experience & Honors"
    url = "/experience/"
    weight = 30

  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 40

  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 50
